### ISSUE TITLE
How to deal with shape-dependent systematics?

### ISSUE THREAD

**Issue by TAOYi92** [zfit/zfit#494] opened 2023-10-10 07:23 UTC
Hi all,

`zfit` is a great project for experimental particle physics. And I would like to say thank you first to the developers.

I have a technique question on how to deal with shape-dependent uncertainties (sth. like "HIstoSys" in `RooStats`).
In my case, I am trying to do a 2-dimensional fit with both overall systematics and shape-dependent systematics.
I guess the idea may be loading the nominal PDF and up/down 1σ PDF at first, and then doing a proper interpolation use these three PDFs with a nuisance parameter. How to implement it in `zfit`?

Thanks in advance!

**Comment by jonas-eschle** [comment] 2023-10-10 08:56
Hi taoy, thanks for the nice words, glad to hear!
I think what you want to do is called "morphing"? There is a PDF in zfit that does this (however, you may need to tell it explicitily how to restrain the parameters).

An example can be found in the binned fits guide here: https://zfit-tutorials.readthedocs.io/en/master/tutorials/components/33%20-%20Binned%20fits.html#modifiers

Does that help?

**Comment by TAOYi92** [comment] 2023-10-11 09:29
Hi Jonas!

Thank you for the instruction and guide provided!
It works smoothly without errors by following the example using `SplineMorphingPDF` (with some effort to test).

However, from my fitting result, the error seems only to contain the statistical error, like:
```
name             value  (rounded)        hesse    at limit
-------------  ------------------  -----------  ----------
bkg1_yield               0.498191  +/-   0.059       False
bkg2_yield               0.298924  +/-   0.034       False
bkg3_yield                149.729  +/-      12       False
bkg4_yield                192.101  +/-      10       False
```
If so, how do I get the whole error then? Am I doing something wrong?

Many thanks,
Yi
  
  
PS.The code for an unbinned likelihood fit I used is attached here(Ignore several unimportant lines):
```python
# Load data.
obs_x         = zfit.Space('X', limits=(x_min, x_max))
obs_y         = zfit.Space('Y', limits=(y_min, y_max))
obs           = obs_x * obs_y
data          = zfit.Data.from_numpy(obs=obs, array=data_points)  # data_points is a 2d ndarray

# Load PDFs.
bkg1_yield    = zfit.Parameter("bkg1_yield", 5, 0, 20)
bkg1_pdf      = zfit.pdf.HistogramPDF(data=h1, extended=bkg1_yield)
bkg1_prior    = 5.2
bkg1_csn_a    = zfit.constraint.GaussianConstraint(
    bkg1_yield, observation = bkg1_prior, uncertainty = bkg1_prior * 0.56)
bkg1_csn_b    = zfit.constraint.GaussianConstraint(
    bkg1_yield, observation = bkg1_prior, uncertainty = bkg1_prior * 0.12)
bkg1_alpha    = zfit.Parameter('bkg1_alpha', 0, -3, 3)
bkg1_histpdfs = {0: bkg1_pdf, 1: bkg1_pdf_up}
bkg1_sys_pdf  = zfit.pdf.SplineMorphingPDF(bkg1_alpha, bkg1_histpdfs, extended=bkg1_yield)

...  # Similar for bkg2,3,4

model = zfit.pdf.BinnedSumPDF([bkg1_sys_pdf, bkg2_sys_pdf, bkg3_sys_pdf, bkg4_sys_pdf])
constraint_lst = [
    bkg1_csn_a, bkg2_csn_a, bkg3_csn_a, bkg4_csn_a,
    bkg1_csn_b, bkg2_csn_b, bkg3_csn_b, bkg4_csn_b
]

# Fit.
nll = zfit.loss.ExtendedUnbinnedNLL(model, data, constraints=constraint_lst)
minimizer = zfit.minimize.Minuit(gradient=True)
result = minimizer.minimize(nll)
result.hesse();
print(result.params)
```

**Comment by jonas-eschle** [comment] 2023-10-11 09:58
Hm, what exactly do you mean by "statistical error"? Or what would you expect to get out exactly?
Do you mean the alpha parameter and uncertainties on it?

I just tried to "run" the minimal example, and alpha, as well as the yield, are fit. (just a toy sample data)

**Comment by TAOYi92** [comment] 2023-10-11 10:07
> Do you mean the alpha parameter and uncertainties on it?

Yes. The current output error is too small and does not change when I play with the uncertainty given through constraint.

**Comment by jonas-eschle** [comment] 2023-10-11 13:00
Hm, so I tried with a minimal example, but hard to get something working similarily. In general, things you do seem to look correct, but maybe there is something weird somewhere?
Can you maybe post the full script, I'll try to reproduce things more neatly then.
Or maybe contact me on e-mail or Mattermost (assuming your CERN too?) and we can iterate there?

**Comment by TAOYi92** [comment] 2023-10-11 14:18
I send you an email and keep debugging my script and I think I am getting closer to the final solution. 
Let's focus on one parameter `bkg1_yield`:
```
bkg1_yield               0.498191  +/-   0.059         (1)
```
In my minimal example above, I use two constraints `bkg1_csn_a` and `bkg1_csn_b` for parameter `bkg1_yield`, just trying to put two independent relative uncertainties (56% and 12%). But I found that the fit error is only determined by the second uncertainty (0.059 / 0.498191 $\approx$ 12%). I confirm my guess by removing the second uncertainty and then get
```
bkg1_yield               0.460735  +/-    0.28         (2)
```
which is close to 56% !!

This means what I was confused about, was not the "statistical error", but the overwritten of the systematics.
But then how do I properly pass in two independent relative uncertainties? I can do a “square root of a sum of squares” manually, but maybe there is a better/more elegant way?

**Comment by jonas-eschle** [comment] 2023-10-23 10:06
I'll just continue here so that it's kept for other people (and sorry for the late answer)

I've just tested it for myself and it seems to work, hower, just to note, this is a hard to see effect (especially with such different constraints.

So, my test is, doing a fit with no constraint, vs with one constraint (cross-check, this should now notably change the uncertainty), vs with two contstraints (the same constraint as before, i.e. the same uncertainty, mean).

The latter reduces the uncertainty for me even more, how is that for you?

I think the "problem" is maybe in that wide constraint: If the uncertainty goes from ~60 to 30 due to the additional constraint of 12% width, then I would estimate that a constraint with ~56% width would reduce that to about 27ish at max, rather 28-29 I would assume, so barely noticable.

FYI: in the code, the extended NLL is summed here https://github.com/zfit/zfit/blob/develop/zfit/core/loss.py#L1006 that calls this one here https://github.com/zfit/zfit/blob/develop/zfit/core/loss.py#L835, meaning it takes into account either all or none of the constraints

**Comment by jonas-eschle** [comment] 2024-02-29 21:58
Hi @TAOYi92 , I was wondering if there are any news on this? Could you verify that all constraints are taken into account?

**Comment by jonas-eschle** [comment] 2024-03-06 22:11
Closing, just tag me if you want this reopened

**Closed by jonas-eschle** 2024-03-06 22:11 UTC
