### ISSUE TITLE
fit failing with NaNs

### ISSUE THREAD

**Issue by niklasnolte** [zfit/zfit#195] opened 2020-01-28 15:40 UTC
Should a fit fail more gracefully in case of NaN values?  
I'd like it if it sais something along the lines of  
`the minimization failed, please review your model and starting values`
```
RuntimeError: exception was raised in user function
User function arguments:
      frac_B0_1 = +nan
         N_B0_3 = +nan
      mean_B0_1 = +nan
    sigma1_B0_1 = +nan
    sigma2_B0_1 = +nan
Original python exception in user function:
InvalidArgumentError: assertion failed: [nan]
	 [[node Assert_37/AssertGuard/Assert (defined at /home/nnolte/.local/lib/python3.7/site-packages/tensorflow_core/python/framework/ops.py:1748) ]]
```

Or is there another underlying problem i'm not seeing?

**Comment by mayou36** [comment] 2020-01-28 15:47
Thanks a lot for pointing this out! There are a few options to change this behavior, e.g. to simply "ignore" it (e.g. in case of toys).

The message actually sounds like a nice default, slightly extended:

"The minimization failed due to NaNs being produced in the loss. This is most probably caused by negative values returned from the PDF. Changing the initial values/stepsize of the parameters can solve this problem. Also check your model (if custom) for problems. For more information, also visit https://github.com/zfit/zfit/wiki/FAQ#fitting-and-minimization"

What do you think?

**Comment by niklasnolte** [comment] 2020-01-28 16:14
sounds good :+1:

**Comment by mayou36** [comment] 2020-01-28 17:38
Pushed, you can try it out by installing the newest development version as described in https://github.com/zfit/zfit#installing if you want to try it out.
Please feel free to close the issue.

**Closed** 2020-01-28 18:12 UTC
